/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Assume;
import org.junit.Test;
import org.junit.runner.RunWith;
import smallcheck.annotations.Property;
import smallcheck.SmallCheckRunner;

import java.util.List;

import static org.junit.Assert.*;


@RunWith(SmallCheckRunner.class)
public class StandardTypes {

    @Test
    public void blub() {
        assertEquals(5, 2 + 2);
    }

    @Property
    public void test(int x, long y) {
        assertEquals(x + y, x * y);
    }


    @Property
    public void testArray(Integer[] ar) {
        int sum = 0;
        for (int i : ar) {
            sum += i;
        }
        assertTrue(sum != 10);
    }

    @Property
    public void testString(String s) {
        assertTrue(s.length() < 4);
    }

    @Property
    public void testStringList(List<String> strings) {
        assertEquals(0, strings.size() > 3 ? strings.get(3).length() : 0);
    }

    @Property
    public void testAssume(List<String> x, List<String> y) {
        Assume.assumeTrue(x.contains("b"));
        Assume.assumeTrue(y.contains("b"));
        assertEquals(x, y);
    }

    @Property
    public void testAssume2(List<String> x) {
        System.out.println(x);
        Assume.assumeTrue(x.size() > 4);
        assertEquals(1, 2);
    }
}
